--CREATE DATABASE QUANLYPHONGKHAM_TIEMCHUNG

CREATE TABLE BENHNHAN 
(
	MaBN CHAR(5) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50),
	NgaySinh DATE,
	GioiTinh NVARCHAR(3) CHECK (GioiTinh IN ('Nam', N'Nữ')),
	DiaChi NVARCHAR(90),
	SoDienThoai CHAR(10) CHECK (LEN(SoDienThoai) = 10 AND SoDienThoai LIKE '[0-9]%'),
)
CREATE TABLE NHANVIEN
(
	MaNV CHAR(5) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50),
	GioiTinh NVARCHAR(3) CHECK (GioiTinh IN ('Nam', N'Nữ')),
	ChucVu NVARCHAR(30),
	DiaChi NVARCHAR(90),
	SoDienThoai CHAR(10) CHECK (LEN(SoDienThoai) = 10 AND SoDienThoai LIKE '[0-9]%'),
)


CREATE TABLE NHACUNGCAP
(
	MaNCC CHAR(5) NOT NULL PRIMARY KEY,
	TenNCC NVARCHAR(50),
	DiaChi NVARCHAR(60),
	SoDienThoai CHAR(10) CHECK (LEN(SoDienThoai) = 10 AND SoDienThoai LIKE '[0-9]%'),
)

CREATE TABLE LOAIVACCINE
(
	MaLoai CHAR(5) NOT NULL PRIMARY KEY,
	TenLoai NVARCHAR(50),
)

CREATE TABLE VACCINE
(
	MaVC CHAR(5) NOT NULL PRIMARY KEY ,
	MaLoai CHAR(5),
	FOREIGN KEY(MaLoai) REFERENCES LOAIVACCINE(MaLoai),
	TenVC NVARCHAR(50),
	NgaySX DATE ,
	HanSuDung DATE,
	SoLuongTon INT CHECK (SoLuongTon >= 0),
	Gia INT CHECK (Gia >= 0) DEFAULT 0,
	CHECK (HanSuDung > NgaySX)  
)

CREATE TABLE PHIEUNHAP
(
	MaPN CHAR(5) NOT NULL PRIMARY KEY,
	NgayNhap DATE,
	MaNCC CHAR(5) NOT NULL ,
	FOREIGN KEY(MaNCC) REFERENCES NHACUNGCAP(MaNCC),
)

CREATE TABLE CHITIETPHIEUNHAP
(
	MaPN CHAR(5) NOT NULL ,
	MaVC CHAR(5) NOT NULL ,
	PRIMARY KEY(MaPN,MaVC),
	FOREIGN KEY(MaPN) REFERENCES PHIEUNHAP(MaPN),
	FOREIGN KEY(MaVC) REFERENCES VACCINE(MaVC),
	SoLuong INT ,
	DonGia FLOAT,
)

CREATE TABLE HOADON
(
	MaHD CHAR(5) NOT NULL PRIMARY KEY ,
	NgayLap DATE,
	MaBN CHAR(5) NOT NULL,
	FOREIGN KEY(MaBN) REFERENCES BENHNHAN(MaBN),
	MaNV CHAR(5) NOT NULL,
	FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV),
	TongTien FLOAT CHECK (TongTien >= 0),
)

CREATE TABLE CHITIETHOADON
(
	MaHD CHAR(5) NOT NULL,
	MaVC CHAR(5) NOT NULL,
	PRIMARY KEY(MaHD,MaVC),
	FOREIGN KEY(MaHD) REFERENCES HOADON(MaHD),
	FOREIGN KEY(MaVC) REFERENCES VACCINE(MaVC),
	SOLUONG INT,
	DONGIA FLOAT,
)
CREATE TABLE LICHTIEM 
(
    MaLT CHAR(5) NOT NULL,
    MaHD CHAR(5) NOT NULL,
    MaBN CHAR(5),
    MaVC CHAR(5),
    NgayHenTiem DATE,
    TrangThai NVARCHAR(15),
    PRIMARY KEY (MaLT, MaHD), 
    FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),  
    FOREIGN KEY (MaBN) REFERENCES BENHNHAN(MaBN), 
    FOREIGN KEY (MaVC) REFERENCES VACCINE(MaVC)
);


CREATE TABLE GHINHANTIEMCHUNG
(
	MaBN CHAR(5) NOT NULL,
	FOREIGN KEY(MaBN) REFERENCES BENHNHAN(MaBN),
	MaVC CHAR(5) NOT NULL,
	FOREIGN KEY(MaVC) REFERENCES VACCINE(MaVC),
	MaNV CHAR(5) NOT NULL,
	FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV),
	MaLT CHAR(5) NOT NULL,
	MaHD CHAR(5) NOT NULL,
	FOREIGN KEY (MaLT, MaHD) REFERENCES LICHTIEM(MaLT, MaHD),
	NgayTiem DATE,
	PRIMARY KEY(MaBN, MaVC, MaLT,MaNV)
);



CREATE TABLE TAIKHOAN
(
	UserName VARCHAR(15) NOT NULL PRIMARY KEY,
	Pass VARCHAR(30) NOT NULL,
	ChucVu INT NOT NULL,
)
-------------------------------------------------------------------------------
--------------------------------Tạo_Mã_Tự_Động---------------------------------
-------------------------------------------------------------------------------

--Mã bệnh nhân tự động
CREATE SEQUENCE SEQ_MaBN AS INT START WITH 1 INCREMENT BY 1;
ALTER TABLE BENHNHAN
ADD CONSTRAINT DF_MaBN
DEFAULT 'BN' + RIGHT('000' + CAST(NEXT VALUE FOR SEQ_MaBN AS VARCHAR(3)), 3) FOR MaBN;

--Mã nhân viên tự động
CREATE SEQUENCE SEQ_MaNV AS INT START WITH 1 INCREMENT BY 1;
ALTER TABLE NHANVIEN
ADD CONSTRAINT DF_MaNV
DEFAULT 'NV' + RIGHT('000' + CAST(NEXT VALUE FOR SEQ_MaNV AS VARCHAR(3)), 3) FOR MaNV;

--Mã nhà cung cấp tự động
CREATE SEQUENCE SEQ_MaNCC AS INT START WITH 1 INCREMENT BY 1;
ALTER TABLE NHACUNGCAP
ADD CONSTRAINT DF_MaNCC
DEFAULT 'NCC' + RIGHT('00' + CAST(NEXT VALUE FOR SEQ_MaNCC AS VARCHAR(2)), 2) FOR MaNCC;

--Mã LOẠI VACCINE tự động
CREATE SEQUENCE SEQ_MaLoaiVC AS INT START WITH 1 INCREMENT BY 1;
ALTER TABLE LOAIVACCINE
ADD CONSTRAINT DF_MaLoaiVVC
DEFAULT 'LV' + RIGHT('000' + CAST(NEXT VALUE FOR SEQ_MaLoaiVC AS VARCHAR(3)), 3) FOR MaLoai;

--Mã VACCINE tự động
CREATE SEQUENCE SEQ_MaVC AS INT START WITH 1 INCREMENT BY 1;
ALTER TABLE VACCINE
ADD CONSTRAINT DF_MaVC
DEFAULT 'VC' + RIGHT('000' + CAST(NEXT VALUE FOR SEQ_MaVC AS VARCHAR(3)), 3) FOR MaVC;

--Mã PHIẾU NHẬP tự động
CREATE SEQUENCE SEQ_MaPN AS INT START WITH 1 INCREMENT BY 1;
ALTER TABLE PHIEUNHAP
ADD CONSTRAINT DF_MaPN
DEFAULT 'PN' + RIGHT('000' + CAST(NEXT VALUE FOR SEQ_MaPN AS VARCHAR(3)), 3) FOR MaPN;

--Mã HOÁ ĐƠN tự động 
CREATE SEQUENCE SEQ_MaHD AS INT START WITH 1 INCREMENT BY 1;
ALTER TABLE HOADON
ADD CONSTRAINT DF_MaHD
DEFAULT 'HD' + RIGHT('000' + CAST(NEXT VALUE FOR SEQ_MaHD AS VARCHAR(3)), 3) FOR MaHD;

--Mã LỊCHTIÊM tự động 
CREATE SEQUENCE SEQ_MaLT AS INT START WITH 1 INCREMENT BY 1;
ALTER TABLE LICHTIEM
ADD CONSTRAINT DF_MaLT
DEFAULT 'LT' + RIGHT('000' + CAST(NEXT VALUE FOR SEQ_MaLT AS VARCHAR(3)), 3) FOR MaLT;

-----------------------------------------------------------------------
--------------------------------TRIGER---------------------------------
-----------------------------------------------------------------------

--LẤY GIÁ CHOCHITIETHOADON TỪ VACCINE
GO 
CREATE TRIGGER TG_LAYDONGIACHOCTHD
ON CHITIETHOADON
FOR INSERT,UPDATE
AS
BEGIN
	UPDATE CHITIETHOADON
	SET CHITIETHOADON.DONGIA = VC.Gia
	FROM VACCINE VC
	WHERE VC.MaVC = CHITIETHOADON.MaVC
END
-- tự tính tổng tiền hoá đơn 
GO
CREATE TRIGGER TG_TINHTONGTIEN
ON CHITIETHOADON
FOR INSERT, UPDATE
AS
BEGIN
    UPDATE HOADON
    SET TongTien = (
        SELECT SUM(SOLUONG * DONGIA) 
        FROM CHITIETHOADON 
        WHERE MaHD IN (SELECT MaHD FROM inserted)
    )
    WHERE MaHD IN (SELECT MaHD FROM inserted);
END


--TỰ TẠO LỊCH TIÊM KHI CÓ HOÁ ĐƠN
GO 
CREATE TRIGGER TG_TAOLICHTIEMKHITHEMHOADON
ON HOADON
FOR INSERT
AS
BEGIN
	INSERT INTO LICHTIEM([MaHD], [MaBN], [TrangThai])
	SELECT i.MaHD, i.MaBN, N'Chưa tiêm'
    FROM INSERTED i;
END

--TỰ Thêm MÃ VACCINE vào LỊCH TIÊM KHI Thêm chi tiết hoá đơn
GO 
CREATE TRIGGER TG_THEMMAVCVAOLICHTIEM
ON CHITIETHOADON
FOR INSERT
AS
BEGIN
    UPDATE LICHTIEM
    SET LICHTIEM.MaVC = i.MaVC
    FROM LICHTIEM l
    JOIN INSERTED i ON l.MaHD = i.MaHD;
END
GO


--Cộng số lượng tồn trong vaccine
GO
CREATE TRIGGER TG_CONGSOLUONGTONCUAVACCINE
ON CHITIETPHIEUNHAP
FOR INSERT, UPDATE
AS
BEGIN
    UPDATE VACCINE
    SET SoLuongTon = (SELECT SUM(CT.SoLuong) 
                      FROM CHITIETPHIEUNHAP CT
                      JOIN inserted i ON CT.MaVC = i.MaVC
                      WHERE VACCINE.MaVC = i.MaVC)
    WHERE MaVC IN (SELECT MaVC FROM inserted);
END


--Sau khi thêm GHINHANTIEMCHUNG, cập nhật TrangThai trong bảng LICHTIEM.
GO
CREATE TRIGGER TG_CAPNHAPTRANGTHAILICHTIEM
ON GHINHANTIEMCHUNG
FOR INSERT
AS
BEGIN
    IF NOT EXISTS (SELECT * FROM inserted i JOIN LICHTIEM LT ON LT.MaLT = I.MaLT WHERE i.MaVC = LT.MaVC AND LT.MaBN =i.MaBN AND LT.MaVC =I.MaVC)
    BEGIN
        PRINT N'Dữ liệu không hợp lệ! Không khớp với lịch tiêm.';
        ROLLBACK TRAN
    END;
	UPDATE LICHTIEM
	SET TrangThai = N'Đã tiêm'
	WHERE MaLT = (SELECT MaLT FROM inserted) AND MaVC = (SELECT MaVC FROM inserted ) AND MaBN = (SELECT MaBN FROM inserted)
END

-- Kiểm tra số lượng vaccine trước khi thêm/cập nhật CHITIETHOADON.
GO
CREATE TRIGGER TG_KiemTraSoLuongVaccine
ON CHITIETHOADON
FOR INSERT, UPDATE
AS
BEGIN
	IF (SELECT SOLUONG FROM inserted) > (SELECT SoLuongTon FROM VACCINE WHERE MaVC = (SELECT MaVC FROM inserted))
		BEGIN 
		PRINT N'Số lượng Vaccine còn lại không đủ'
		ROLLBACK TRAN
	END
    -- Cập nhật số lượng tồn kho cho từng vaccine
    UPDATE VACCINE
    SET SoLuongTon = SoLuongTon - (SELECT SUM(SOLUONG) FROM CHITIETHOADON WHERE MaVC = (SELECT MaVC FROM inserted))
    FROM VACCINE V
    JOIN inserted I ON I.MaVC = V.MaVC;
END


--SELECT * FROM CHITIETHOADON
--INSERT INTO CHITIETHOADON ([MaHD], [MaVC], [SOLUONG], [DONGIA]) VALUES
--('HD0002','VC0001',101,'50000')



----------------------------------------------------------------------
--------------------------Procedures----------------------------------
----------------------------------------------------------------------

--ThemLichTiem(@MaLT, @MaVC,@MaBN @NgayHenTiem)
GO
CREATE PROC PR_ThemLichTiem @MaLT CHAR(5), @MaVC CHAR(5),@MaNV CHAR(5),@MaBN CHAR(5), @NgayHenTiem DATE
AS
	IF EXISTS (SELECT * FROM LICHTIEM WHERE MaLT= @MaLT)
		BEGIN
			PRINT N'Mã lịch tiêm đã tồn tại'
		END
	ELSE IF NOT EXISTS ( SELECT * FROM LICHTIEM WHERE MaBN = @MaBN and MaVC =@MaVC )
		BEGIN
			PRINT N'Dử liệu không đúng'
		END
	ELSE
		BEGIN 
			INSERT INTO LICHTIEM([MaLT], [MaBN], [MaVC], [NgayHenTiem], [TrangThai]) VALUES(@MaLT,@MaBN,@MaVC,@NgayHenTiem,'Chưa tiêm')
		END
	
--exec PR_ThemLichTiem 'LT001','VC0006','NV0001','BN0002','2023-12-02'

--select * from LICHTIEM
	

